# Generated by Django 5.2.4 on 2025-07-14 13:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='이름', max_length=100)),
                ('age', models.IntegerField(blank=True, help_text='나이', null=True)),
                ('bio', models.TextField(help_text='짧은 자기소개', max_length=500)),
                ('fun_fact', models.CharField(blank=True, help_text='재미있는 사실 한 가지', max_length=200)),
                ('scanned_people', models.ManyToManyField(blank=True, related_name='scanned_by', to='profiles.person')),
            ],
        ),
    ]
