# Generated by Django 5.1.3 on 2025-07-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="auth_token",
            field=models.CharField(
                blank=True,
                help_text="인증된 기기에만 발급되는 비밀 토큰",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="is_authenticated",
            field=models.BooleanField(
                default=False, help_text="이 사용자가 기기 인증을 완료했는지 여부"
            ),
        ),
    ]
