# Generated by Django 5.1.3 on 2025-07-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_person_auth_token_person_is_authenticated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="bio",
            field=models.TextField(
                blank=True, help_text="짧은 자기소개", max_length=500
            ),
        ),
    ]
