# Generated by Django 5.1.3 on 2025-08-09 13:48

import ckeditor_uploader.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='라운드 번호')),
                ('question', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='문제')),
                ('answer', models.CharField(max_length=255, verbose_name='정답')),
                ('completion_message', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='정답 시 메시지')),
            ],
            options={
                'verbose_name': '게임 문제',
                'verbose_name_plural': '게임 문제 목록',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장소 이름')),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR코드 고유ID')),
                ('location_hint', models.TextField(blank=True, verbose_name='장소 힌트')),
                ('location_answer', models.CharField(blank=True, max_length=100, verbose_name='장소 정답 (팀이 다음 장소를 찾을 때 입력)')),
            ],
            options={
                'verbose_name': '게임 장소',
                'verbose_name_plural': '게임 장소 목록',
            },
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True, verbose_name='팀 이름')),
                ('unique_code', models.CharField(max_length=4, unique=True, verbose_name='팀 고유번호 (4자리)')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('current_round', models.PositiveIntegerField(default=1, verbose_name='현재 라운드')),
            ],
            options={
                'verbose_name': '게임 팀',
                'verbose_name_plural': '게임 팀 목록',
            },
        ),
        migrations.CreateModel(
            name='TeamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(default=1, verbose_name='라운드 번호')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.gameroom', verbose_name='장소')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.gameteam', verbose_name='팀')),
            ],
            options={
                'verbose_name': '팀별 스케줄',
                'verbose_name_plural': '팀별 스케줄 표',
                'unique_together': {('team', 'round_number')},
            },
        ),
    ]
