# Generated by Django 5.1.3 on 2025-08-07 15:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GameProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(help_text='1~7 사이의 숫자를 입력하세요.', unique=True, verbose_name='라운드 번호')),
                ('story', models.TextField(blank=True, verbose_name='스토리')),
                ('question', models.TextField(verbose_name='문제')),
                ('answer', models.CharField(max_length=255, verbose_name='정답')),
                ('points', models.PositiveIntegerField(default=10, verbose_name='획득 점수')),
            ],
            options={
                'verbose_name': '게임 문제',
                'verbose_name_plural': '게임 문제 목록',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='장소 이름')),
                ('qr_code_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR코드 고유ID')),
            ],
            options={
                'verbose_name': '게임 장소',
                'verbose_name_plural': '게임 장소 목록',
            },
        ),
        migrations.CreateModel(
            name='GameTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100, unique=True, verbose_name='팀 이름')),
                ('unique_code', models.CharField(blank=True, max_length=4, unique=True, verbose_name='팀 고유번호 (4자리)')),
                ('score', models.PositiveIntegerField(default=0, verbose_name='총 점수')),
            ],
            options={
                'verbose_name': '게임 팀',
                'verbose_name_plural': '게임 팀 목록',
            },
        ),
        migrations.CreateModel(
            name='GameTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.PositiveIntegerField(unique=True, verbose_name='라운드 번호')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간 (KST)')),
                ('end_time', models.DateTimeField(verbose_name='종료 시간 (KST)')),
            ],
            options={
                'verbose_name': '게임 시간',
                'verbose_name_plural': '게임 시간 목록',
                'ordering': ['round_number'],
            },
        ),
        migrations.CreateModel(
            name='TeamSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.gameroom', verbose_name='장소')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.gameteam', verbose_name='팀')),
                ('timeslot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recreation.gametimeslot', verbose_name='시간')),
            ],
            options={
                'verbose_name': '팀별 스케줄',
                'verbose_name_plural': '팀별 스케줄 표',
                'unique_together': {('team', 'timeslot')},
            },
        ),
    ]
